name: Upload Python Package

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest-cov
        python -m pip install .
    - name: Build package
      run: |
        pytest -s --cov=utils tests/
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ 50b104cc-7450-408c-99d3-88e43daa1301 }} # not required for public repos
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
      
