name: Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest-cov
        python -m pip install .
    - name: Test
      run: |
        pytest -s --cov=gro-exp --cov-report=xml tests/
    - name: Code coverage
      uses: codecov/codecov-action@v1
